name: Frpc Android Lib Build
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
      - name: Config And Build
        run: |
          export ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk/26.1.10909125
          go install golang.org/x/mobile/cmd/gomobile@latest
          git clone https://github.com/fatedier/frp $(go env GOPATH)/src/github.com/fatedier/frp
          cd $(go env GOPATH)/src/github.com/fatedier/frp
          wget https://raw.githubusercontent.com/thisdk/frpc-android-lib/main/main.go -O cmd/frpc/sub/root.go
          wget https://raw.githubusercontent.com/thisdk/frpc-android-lib/main/root.go -O cmd/frpc/main.go
          go get golang.org/x/mobile/cmd/gobind
          go mod download
          gomobile init
          gomobile bind -target=android/arm64 ./cmd/frpc
      - uses: actions/upload-artifact@v3
        with:
          name: frpc-android-lib
          path: /home/runner/go/src/github.com/fatedier/frp/sub.aar
